//! Commented TOML generation for wizard-built configs.

use std::fmt::Write as _;
use std::net::Ipv4Addr;

pub struct ServerParams {
    pub listen: String,
    pub max_clients: usize,
    pub cipher: String,
    pub key_file: String,
    pub peers: Vec<PeerParams>,
    pub subnet: Ipv4Addr,
    pub prefix: u8,
    pub gateway: bool,
    pub external_interface: Option<String>,
    pub transport: String,
    pub tls_sni: Option<String>,
    pub tls_cert_file: Option<String>,
    pub tls_key_file: Option<String>,
}

pub struct PeerParams {
    pub public_key: String,
    pub name: String,
}

pub struct ClientParams {
    pub endpoint: String,
    pub cipher: String,
    pub key_file: String,
    pub server_public_key: String,
    pub address: Ipv4Addr,
    pub prefix: u8,
    pub route_all: bool,
    pub dns_servers: Vec<String>,
    pub transport: String,
    pub tls_sni: Option<String>,
}

/// Render a top-level `[tls]` section, or an empty string for non-TLS transports.
/// `cert_file`/`key_file` are server-only and emitted only when both are set.
fn tls_section(
    transport: &str,
    sni: Option<&str>,
    cert_file: Option<&str>,
    key_file: Option<&str>,
) -> String {
    if transport != "tls" {
        return String::new();
    }
    let sni = sni.unwrap_or("www.cloudflare.com");
    let mut s = String::from(
        "\n# TLS transport: a real TLS 1.3 session over TCP with the Noise handshake\n\
         # riding inside. The SNI should be a plausible host so the ClientHello blends\n\
         # in with ordinary HTTPS. Both ends must use the same transport.\n[tls]\n",
    );
    let _ = writeln!(s, "sni = \"{}\"", sni);
    if let (Some(c), Some(k)) = (cert_file, key_file) {
        let _ = writeln!(
            s,
            "# Optional: present your own certificate instead of an auto self-signed one.\n\
             cert_file = \"{}\"\nkey_file = \"{}\"",
            c, k
        );
    }
    s
}

/// First usable host address in the subnet (the server's address)
pub fn server_address(subnet: Ipv4Addr) -> Ipv4Addr {
    Ipv4Addr::from(u32::from(subnet) + 1)
}

/// N-th client address in the subnet (.2, .3, ...)
pub fn client_address(subnet: Ipv4Addr, index: usize) -> Ipv4Addr {
    Ipv4Addr::from(u32::from(subnet) + 2 + index as u32)
}

pub fn render_server(p: &ServerParams) -> String {
    let mut out = String::new();
    let _ = write!(
        out,
        r#"# 2cha VPN Server Configuration v1.0
# Generated by: 2cha init server
# Usage: sudo 2cha server -c server.toml

[server]
listen = "{listen}"
max_clients = {max_clients}
# Obfuscation transport: "quic" (UDP) or "tls" (TCP). Must match clients.
transport = "{transport}"

[tun]
name = "tun0"
mtu = 1420

[crypto]
cipher = "{cipher}"
private_key_file = "{key_file}"
"#,
        listen = p.listen,
        max_clients = p.max_clients,
        transport = p.transport,
        cipher = p.cipher,
        key_file = p.key_file,
    );

    out.push_str(&tls_section(
        &p.transport,
        p.tls_sni.as_deref(),
        p.tls_cert_file.as_deref(),
        p.tls_key_file.as_deref(),
    ));

    out.push('\n');
    if p.peers.is_empty() {
        out.push_str(
            "# Authorized clients. Get a client's key with: 2cha pubkey client.key\n\
             # WARNING: the server refuses to start without at least one peer.\n\
             # [[peers]]\n\
             # public_key = \"CLIENT_PUBLIC_KEY_BASE64\"\n\
             # name = \"laptop\"\n",
        );
    } else {
        out.push_str("# Authorized clients (whitelist)\n");
        for peer in &p.peers {
            let _ = write!(
                out,
                "[[peers]]\npublic_key = \"{}\"\nname = \"{}\"\n\n",
                peer.public_key, peer.name
            );
        }
        out.pop();
    }

    let _ = write!(
        out,
        r#"
[ipv4]
enable = true
address = "{address}"
prefix = {prefix}

[ipv6]
enable = false

[gateway]
ip_forward = {gw}
masquerade_v4 = {gw}
external_interface = "{ext_iface}"

[timeouts]
# Drop a client session after this many seconds without traffic
session = 180

[logging]
level = "info"
"#,
        address = server_address(p.subnet),
        prefix = p.prefix,
        gw = p.gateway,
        ext_iface = p.external_interface.as_deref().unwrap_or("eth0"),
    );
    out
}

pub fn render_client(p: &ClientParams) -> String {
    let mut dns_v4 = String::from("[");
    for (i, s) in p.dns_servers.iter().enumerate() {
        if i > 0 {
            dns_v4.push_str(", ");
        }
        let _ = write!(dns_v4, "\"{}\"", s);
    }
    dns_v4.push(']');

    let tls = tls_section(&p.transport, p.tls_sni.as_deref(), None, None);

    format!(
        r#"# 2cha VPN Client Configuration v1.0
# Generated by: 2cha init client
# Usage: sudo 2cha up -c client.toml

[client]
# Server address: IP:port or domain:port
server = "{endpoint}"
# Obfuscation transport: "quic" (UDP) or "tls" (TCP). Must match the server.
transport = "{transport}"
{tls}
[tun]
name = "tun0"
mtu = 1420

[crypto]
cipher = "{cipher}"
private_key_file = "{key_file}"
# The server's public key (2cha pubkey server.key on the server)
server_public_key = "{server_public_key}"

[ipv4]
enable = true
address = "{address}"
prefix = {prefix}
# Route all traffic through the VPN
route_all = {route_all}

[ipv6]
enable = false

[dns]
servers_v4 = {dns_v4}

[logging]
level = "info"
"#,
        endpoint = p.endpoint,
        transport = p.transport,
        tls = tls,
        cipher = p.cipher,
        key_file = p.key_file,
        server_public_key = p.server_public_key,
        address = p.address,
        prefix = p.prefix,
        route_all = p.route_all,
        dns_v4 = dns_v4,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn server_params(peers: Vec<PeerParams>) -> ServerParams {
        ServerParams {
            listen: "0.0.0.0:51820".into(),
            max_clients: 256,
            cipher: "chacha20-poly1305".into(),
            key_file: "/etc/2cha/server.key".into(),
            peers,
            subnet: Ipv4Addr::new(10, 8, 0, 0),
            prefix: 24,
            gateway: true,
            external_interface: Some("eth0".into()),
            transport: "quic".into(),
            tls_sni: None,
            tls_cert_file: None,
            tls_key_file: None,
        }
    }

    #[test]
    fn test_render_server_parses() {
        let rendered = render_server(&server_params(vec![PeerParams {
            public_key: twocha_core::encode_public_key(&[7u8; 32]),
            name: "laptop".into(),
        }]));
        let cfg = twocha_core::ServerConfig::parse(&rendered).unwrap();
        assert_eq!(cfg.peers.len(), 1);
        assert_eq!(cfg.ipv4.address.as_deref(), Some("10.8.0.1"));
        assert!(cfg.gateway.ip_forward);
    }

    #[test]
    fn test_render_server_no_peers_parses() {
        let rendered = render_server(&server_params(Vec::new()));
        let cfg = twocha_core::ServerConfig::parse(&rendered).unwrap();
        assert!(cfg.peers.is_empty());
    }

    #[test]
    fn test_render_client_parses() {
        let rendered = render_client(&ClientParams {
            endpoint: "vpn.example.com:51820".into(),
            cipher: "chacha20-poly1305".into(),
            key_file: "/etc/2cha/client.key".into(),
            server_public_key: twocha_core::encode_public_key(&[9u8; 32]),
            address: Ipv4Addr::new(10, 8, 0, 2),
            prefix: 24,
            route_all: true,
            dns_servers: super::super::default_dns_servers(),
            transport: "quic".into(),
            tls_sni: None,
        });
        let cfg = twocha_core::ClientConfig::parse(&rendered).unwrap();
        assert!(cfg.validate().is_ok());
        assert_eq!(cfg.dns.servers_v4.len(), 2);
    }

    #[test]
    fn test_render_server_tls_parses() {
        let mut p = server_params(vec![PeerParams {
            public_key: twocha_core::encode_public_key(&[7u8; 32]),
            name: "laptop".into(),
        }]);
        p.transport = "tls".into();
        p.tls_sni = Some("www.example.com".into());
        let rendered = render_server(&p);
        let cfg = twocha_core::ServerConfig::parse(&rendered).unwrap();
        assert_eq!(cfg.server.transport, twocha_core::TransportKind::Tls);
        assert_eq!(cfg.tls.sni, "www.example.com");
    }

    #[test]
    fn test_render_client_tls_parses() {
        let rendered = render_client(&ClientParams {
            endpoint: "vpn.example.com:443".into(),
            cipher: "chacha20-poly1305".into(),
            key_file: "/etc/2cha/client.key".into(),
            server_public_key: twocha_core::encode_public_key(&[9u8; 32]),
            address: Ipv4Addr::new(10, 8, 0, 2),
            prefix: 24,
            route_all: false,
            dns_servers: Vec::new(),
            transport: "tls".into(),
            tls_sni: Some("www.example.com".into()),
        });
        let cfg = twocha_core::ClientConfig::parse(&rendered).unwrap();
        assert!(cfg.validate().is_ok());
        assert_eq!(cfg.client.transport, twocha_core::TransportKind::Tls);
        assert_eq!(cfg.tls.sni, "www.example.com");
    }

    #[test]
    fn test_addresses() {
        let net = Ipv4Addr::new(10, 8, 0, 0);
        assert_eq!(server_address(net), Ipv4Addr::new(10, 8, 0, 1));
        assert_eq!(client_address(net, 0), Ipv4Addr::new(10, 8, 0, 2));
        assert_eq!(client_address(net, 3), Ipv4Addr::new(10, 8, 0, 5));
    }
}
